DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS ticket_version;

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ticket_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

INSERT INTO ticket (name, quantity) VALUES ('test1', 3000);
INSERT INTO ticket (name, quantity) VALUES ('test2', 3000);
INSERT INTO ticket_version (name, quantity) VALUES ('test3', 3000);