spring:
  application:
    name: spring-concurrency
  datasource:
    url: jdbc:postgresql://localhost:5432/concurrency_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true